### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by zonky2** [heimrichhannot/contao-multi_column_editor#3] opened 2018-09-14 17:34 UTC
Haben MetaModels gefixt, um diesen hübschen Querschläger abzufangen...
https://github.com/heimrichhannot/contao-multi_column_editor/blob/master/classes/Hooks.php#L45

dürfte anderen Erweiterungen ähnlich gehen...

**Comment by Defcon0** [comment] 2018-09-17 08:49
Fixed in https://github.com/heimrichhannot/contao-multi_column_editor/commit/e9a6b6268c963003a8dfb086e31672214cf7d873.

Please note that contao-multi_column_editor is abandoned. https://github.com/heimrichhannot/contao-multi-column-editor-bundle is the current one which is for Contao 4.

What also might be intersting is, how you fixed it in MetaModels.

**Closed as completed by Defcon0** 2018-09-17 08:49 UTC

**Comment by zonky2** [comment] 2018-09-17 09:13
see https://github.com/contao-community-alliance/dc-general/commit/9aed09534b1ef9926d82588242cd6f96c8e5f9a4

**Comment by Defcon0** [comment] 2018-09-17 09:31
Ah ok, thanks. Maybe you could test the extension if it works now? It should, but just to be sure ;-)

**Comment by dmolineus** [comment] 2018-09-18 07:58
Don't you still set a field in dca.fields.NAME to true? Which should cause issues with every extension expecting an array here as it's the expected behaviour in contao...

**Comment by Defcon0** [comment] 2018-09-18 08:03
Ah, I see. I do this since the fields in eval -> multiColumnEditor -> fields don't really exist for Contao. If I remove the "true" and do an ajax call in one of the fields in multi_column_editor, I get the exception from contao that the field doesn't exist.

But if the problem is just that it shouldn't be `true`but `[]`, I can easily fix that. Or would it be better to add the fields to the normal dca automatically but without sql so that we don't have them in the db?

**Comment by dmolineus** [comment] 2018-09-18 08:39
Setting an empty array would be better I think. I don't know how the multi column editor works (I know it needs some hacks to overcome Contao limitations for advanced widgets though), but I think it should be okay to keep an empty array as Contao does not enforce you to have an `inputType` f.e.

**Comment by zonky2** [comment] 2018-09-18 08:49
@Defcon0 What is the reason not to use the MCW or to program your own "MCW"?

**Comment by Defcon0** [comment] 2018-09-18 08:54
OK, fixed in https://github.com/heimrichhannot/contao-multi_column_editor/commit/ced0ab99b309d7cfb5d5ecb8245e30511ab704b1.

Reason for why we built multi column editor is answered in the README.md of this module ;-)

> The module is similar to menatwork/MultiColumnWizard but works in frontend as well (in combination with the form generator module heimrichhannot/contao-formhybrid).

**Comment by zonky2** [comment] 2018-09-18 09:05
o.k. ... we push the MCW to the FE for front-end-editing in MM - see https://github.com/richardhj/contao-multicolumnwizard-frontend
